#! /usr/bin/env python
"""
# ----------------------
# Even Fibonacci numbers
# ----------------------
#
# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.

"""
import sys
import time

start_time = time.time()
a, b, total = 1, 1, 0

# 4Mill Limit
while b <= 4000000:
    # Odd Number
    if b % 2 == 0:
        total += b
    # Fibo Sec
    a, b = b, a + b        
    
print total

end_time = time.time()
print "Exec Time %.10f secs" % (float(end_time - start_time))